import Vita from './Vita'

export default function NarrativeCard({ narrative, loading }) {
  return (
    <div className="metric-card narrative-glow relative overflow-hidden">
      {/* Subtle green gradient backdrop */}
      <div
        className="absolute inset-0 opacity-40 pointer-events-none"
        style={{
          background: 'radial-gradient(ellipse at top left, rgba(0,209,84,0.08) 0%, transparent 60%)',
        }}
      />

      <div className="relative">
        <div className="flex items-center gap-3 mb-4">
          <Vita size="sm" />
          <div>
            <div className="font-bold text-secondary text-base">Vita's analysis</div>
            <div className="label-tag">AI-generated health narrative</div>
          </div>
        </div>

        {loading ? (
          <div className="space-y-2.5">
            {[100, 90, 95, 70].map((w, i) => (
              <div
                key={i}
                className="h-3.5 rounded-full bg-gray-100 animate-pulse"
                style={{ width: `${w}%` }}
              />
            ))}
          </div>
        ) : (
          <p className="text-gray-700 leading-relaxed text-sm">
            {narrative}
          </p>
        )}

        <div className="mt-4 pt-3 border-t border-gray-50 flex items-center gap-1.5">
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
            <circle cx="6" cy="6" r="5" stroke="#00D154" strokeWidth="1.2"/>
            <path d="M4 6l1.5 1.5L8 4.5" stroke="#00D154" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
          <span className="text-[10px] text-gray-400 font-medium tracking-wide">
            Generated by Vita · based on your biometric data
          </span>
        </div>
      </div>
    </div>
  )
}
